[build]
  command = "bun run build"
  functions = ".netlify/functions"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "bun run dev"
  port = 5173
  publish = "build"
